version: '3.8'

services:
  auth-service:
    hostname: auth
    image: webdevops/php-nginx:8.2-alpine
    container_name: auth-service
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./auth-service:/app
      - ./auth-service/nginx/nginx.conf:/opt/docker/etc/nginx/vhost.conf
    networks:
      - marketplace_network
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis

  store-service:
    hostname: store
    image: webdevops/php-nginx:8.2-alpine
    container_name: store-service
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./store-service:/app
      - ./store-service/nginx/nginx.conf:/opt/docker/etc/nginx/vhost.conf
    networks:
      - marketplace_network
    ports:
      - "8081:80"
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace_network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - marketplace_network

networks:
  marketplace_network:
    driver: bridge

volumes:
  postgres_data:

