version: '3.8'

services:
  auth-service:
    image: webdevops/php-nginx:8.2-alpine
    container_name: auth-service
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./auth-service:/app
      - ./auth-service/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - marketplace_network
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace_network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - marketplace_network

networks:
  marketplace_network:
    driver: bridge

volumes:
  postgres_data:

